spring:
  application:
    name: clenzy
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev,local}
  threads:
    virtual:
      enabled: true

# Configuration Keycloak
keycloak:
  auth-server-url: http://clenzy-keycloak:8080
  realm: clenzy
  resource: clenzy-web
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET:}
  admin:
    username: ${KEYCLOAK_ADMIN_USERNAME}
    password: ${KEYCLOAK_ADMIN_PASSWORD}
    client-id: admin-cli

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: WHEN_AUTHORIZED
  metrics:
    tags:
      application: clenzy

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  packages-to-scan: com.clenzy.controller
  paths-to-match: /api/**


