spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/clenzy_dev
    driver-class-name: org.postgresql.Driver
    username: clenzy
    password: clenzy123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/realms/clenzy
          jwk-set-uri: http://localhost:8083/realms/clenzy/protocol/openid-connect/certs
  redis:
    host: clenzy-redis
    port: 6379
    database: 0
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

# Configuration Keycloak
keycloak:
  auth-server-url: http://clenzy-keycloak:8080
  realm: clenzy
  resource: clenzy-web
  credentials:
    secret: ""
  # Configuration pour le client admin
  admin:
    username: admin
    password: admin
    client-id: admin-cli

logging:
  level:
    org.hibernate.SQL: warn
    org.springframework.web: info
    com.clenzy: debug
    org.springframework.security: debug
    org.springframework.web.servlet.mvc.method.annotation: debug

server:
  port: 8080
  address: 0.0.0.0


